version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @vue/cli
  build:
    commands:
      - ./frontend/bin/package-frontend.sh
      - ./bin/package.sh -n frontend
artifacts:
  files:
    - frontend/target/cfn/app/packaged.yml
  discard-paths: yes
